psql

CREATE DATABASE one;

\c one;

CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(255));

CREATE TABLE chirps (id SERIAL PRIMARY KEY, user_id INTEGER, name VARCHAR(255)); #REFERENCES - taken out of INTEGRER

#CREATE TABLE owner (id SERIAL PRIMARY KEY, cow_id INTEGER REFERENCES, farmer_id INTEGER REFERENCES, name VARCHAR(255));
